import Head from 'next/head';
import FooterMenu from './footerMenu/FooterMenu';
import Footer from './mainFooter/footer';
import Navbar from './Navbar';

function Layout({ children }) {
  return (
    <>
      <Head>
        <title>FoodU</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main>
        {children}
        <Footer />
        <FooterMenu />
      </main>
    </>
  );
}
export default Layout;
